/* ==========================================================================
   RISHI RESTAURANTS — Menu Data
   All dish information lives here. Add/edit dishes by editing this array —
   the rest of the site (rendering, filtering, search, cart) reads from it.
   ========================================================================== */

const IMG = (file, w = 500) => `/.netlify/images?url=/img/${file}&w=${w}&fm=webp&q=80`;

const CATEGORIES = [
  { id: "starters", label: "Starters", icon: "fa-drumstick-bite" },
  { id: "soups", label: "Soups", icon: "fa-bowl-rice" },
  { id: "veg-main", label: "Veg Main Course", icon: "fa-seedling" },
  { id: "non-veg-main", label: "Non-Veg Main Course", icon: "fa-kitchen-set" },
  { id: "biryani", label: "Biryani", icon: "fa-bowl-food" },
  { id: "chinese", label: "Chinese", icon: "fa-utensils" },
  { id: "breads", label: "Indian Breads", icon: "fa-bread-slice" },
  { id: "snacks", label: "Snacks", icon: "fa-cookie-bite" },
  { id: "desserts", label: "Desserts", icon: "fa-ice-cream" },
  { id: "beverages", label: "Beverages", icon: "fa-mug-hot" },
];

const MENU_ITEMS = [
  {
    id: "paneer-tikka",
    name: "Paneer Tikka",
    category: "starters",
    veg: true,
    price: 249,
    rating: 4.6,
    special: true,
    desc: "Smoky char-grilled cottage cheese cubes marinated in tandoori spices, served with mint chutney.",
    img: IMG("paneer-tikka.jpg"),
  },
  {
    id: "chicken-65",
    name: "Chicken 65",
    category: "starters",
    veg: false,
    price: 289,
    rating: 4.5,
    desc: "Fiery, deep-fried chicken bites tossed with curry leaves and Madras spices.",
    img: IMG("chicken-65.jpg"),
  },
  {
    id: "tomato-soup",
    name: "Tomato Basil Soup",
    category: "soups",
    veg: true,
    price: 149,
    rating: 4.3,
    desc: "Velvety roasted tomato soup finished with fresh basil and a swirl of cream.",
    img: IMG("tomato-soup.jpg"),
  },
  {
    id: "hot-sour-soup",
    name: "Hot & Sour Chicken Soup",
    category: "soups",
    veg: false,
    price: 179,
    rating: 4.4,
    desc: "A tangy, peppery broth loaded with shredded chicken, mushroom and spring onion.",
    img: IMG("hot-sour-soup.jpg"),
  },
  {
    id: "paneer-butter-masala",
    name: "Paneer Butter Masala",
    category: "veg-main",
    veg: true,
    price: 299,
    rating: 4.7,
    special: true,
    desc: "Soft paneer simmered in a rich, buttery tomato-cashew gravy with a hint of fenugreek.",
    img: IMG("paneer-butter-masala.jpg"),
  },
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    category: "veg-main",
    veg: true,
    price: 259,
    rating: 4.6,
    desc: "Slow-simmered black lentils finished with cream and butter, our signature comfort dish.",
    img: IMG("dal-makhani.jpg"),
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    category: "non-veg-main",
    veg: false,
    price: 349,
    rating: 4.9,
    special: true,
    desc: "Tandoor-roasted chicken in a silky makhani sauce of tomato, butter and cream. A signature classic.",
    img: IMG("butter-chicken.jpg"),
  },
  {
    id: "mutton-rogan-josh",
    name: "Mutton Rogan Josh",
    category: "non-veg-main",
    veg: false,
    price: 429,
    rating: 4.7,
    desc: "Tender mutton slow-cooked in an aromatic Kashmiri red chili and yogurt gravy.",
    img: IMG("mutton-rogan-josh.jpg"),
  },
  {
    id: "chicken-biryani",
    name: "Hyderabadi Chicken Biryani",
    category: "biryani",
    veg: false,
    price: 379,
    rating: 4.8,
    special: true,
    desc: "Fragrant basmati rice layered with marinated chicken, saffron and fried onions, dum-cooked to perfection.",
    img: IMG("chicken-biryani.jpg"),
  },
  {
    id: "veg-biryani",
    name: "Veg Dum Biryani",
    category: "biryani",
    veg: true,
    price: 289,
    rating: 4.5,
    desc: "Basmati rice dum-cooked with garden vegetables, saffron and warm whole spices.",
    img: IMG("veg-biryani.jpg"),
  },
  {
    id: "hakka-noodles",
    name: "Veg Hakka Noodles",
    category: "chinese",
    veg: true,
    price: 219,
    rating: 4.3,
    desc: "Wok-tossed noodles with crisp julienned vegetables in a savory soy garlic sauce.",
    img: IMG("hakka-noodles.jpg"),
  },
  {
    id: "chilli-chicken",
    name: "Chilli Chicken",
    category: "chinese",
    veg: false,
    price: 269,
    rating: 4.6,
    desc: "Crispy chicken tossed with peppers, onions and a spicy Indo-Chinese sauce.",
    img: IMG("chilli-chicken.jpg"),
  },
  {
    id: "butter-naan",
    name: "Butter Naan",
    category: "breads",
    veg: true,
    price: 59,
    rating: 4.7,
    desc: "Classic tandoor-baked flatbread, brushed generously with butter.",
    img: IMG("butter-naan.jpg"),
  },
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    category: "breads",
    veg: true,
    price: 69,
    rating: 4.6,
    desc: "Soft tandoor naan topped with fresh chopped garlic and coriander.",
    img: IMG("garlic-naan.jpg"),
  },
  {
    id: "samosa",
    name: "Samosa (2 pcs)",
    category: "snacks",
    veg: true,
    price: 99,
    rating: 4.5,
    desc: "Crisp golden pastries filled with spiced potatoes and peas, served with tangy chutneys.",
    img: IMG("samosa.jpg"),
  },
  {
    id: "spring-rolls",
    name: "Vegetable Spring Rolls",
    category: "snacks",
    veg: true,
    price: 179,
    rating: 4.4,
    desc: "Crunchy rolls packed with fresh vegetables, served with sweet chili dip.",
    img: IMG("spring-rolls.jpg"),
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    category: "desserts",
    veg: true,
    price: 129,
    rating: 4.8,
    special: true,
    desc: "Warm milk-solid dumplings soaked in rose-cardamom syrup, topped with pistachio.",
    img: IMG("gulab-jamun.jpg"),
  },
  {
    id: "chocolate-brownie",
    name: "Chocolate Brownie with Ice Cream",
    category: "desserts",
    veg: true,
    price: 199,
    rating: 4.7,
    desc: "Warm fudgy brownie paired with a scoop of vanilla ice cream and chocolate drizzle.",
    img: IMG("chocolate-brownie.jpg"),
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    category: "beverages",
    veg: true,
    price: 129,
    rating: 4.6,
    special: true,
    desc: "Thick and creamy yogurt drink blended with sweet Alphonso mango.",
    img: IMG("mango-lassi.jpg"),
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    category: "beverages",
    veg: true,
    price: 69,
    rating: 4.5,
    desc: "Hot spiced tea brewed with cardamom, ginger and cinnamon, served in a clay kulhad.",
    img: IMG("masala-chai.jpg"),
  },
];


// Public reference for checkout/order calculations.
window.RISHI_MENU_ITEMS = MENU_ITEMS;
